services:
  api:
    build: .
    container_name: lyftr-backend-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload